name: "Publish packs"
on:
  workflow_dispatch:

jobs:
  publish_pack:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        pack: ["cpp", "csharp", "go", "java", "ruby", "javascript", "python"]

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Install latest CodeQL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install github/gh-codeql
          gh codeql set-version latest

      - name: "Build and publish pack"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh codeql pack install ${{ matrix.pack }}
          gh codeql pack publish ${{ matrix.pack }}
